### ISSUE TITLE
Logstash support?

### ISSUE THREAD

**Issue by nikhiljay** [sematext/sematext-logsene-android#14]
Hi, I noticed that this android library sends data to Logsene servers. Is it possible to send data to Logstash servers?

**Comment by otisg** [comment]
@nikhiljay Logsene (Sematext) exposes an Elasticsearch API and this library uses that API to send logs to Sematext.  If you can have Logstash servers expose an Elasticsearch API then you can use this library.

I looked at https://www.elastic.co/guide/en/logstash/current/input-plugins.html and don't see anything that would make Logstash look like ES from the outside. 
 https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html does expose an HTP API, but from what I can tell it's different from the ES API.

You could, however, fork this repo and modify or, better yet, issue a PR.
