### ISSUE TITLE
Integrating LogSene Library

### ISSUE THREAD

**Issue by vamshirupeek** [sematext/sematext-logsene-android#15]
Hi LogSene Team, I'm trying to integrate the Library in my App with Min SDK version 16 while syncing my gradle file it throws an error "**Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.sematext:sematext-logsene-android:2.1.0]**". How to resolve this as we have user below SDK Version 21.

**Comment by gr0** [comment]
I'm afraid we don't support SDK below version `19`. You could try porting the library to version `16`, pull requests are more than welcome.
