### ISSUE TITLE
Crash on Android below 4.4.

### ISSUE THREAD

**Issue by oleg-scand** [sematext/sematext-logsene-android#2]
Hello.

The problem is in usage of Objects.requireNonNull() method. [It was added only in api 19](https://developer.android.com/reference/java/util/Objects.html#requireNonNull%28T%29).

Log:

```
java.lang.NoClassDefFoundError: java.util.Objects
at com.sematext.android.Logsene.<init>(Logsene.java:27)
```

**Comment by amir-hadzic** [comment]
Hello, and thanks for reporting the issue, I will look into it.
