### ISSUE TITLE
how to upload logs only in WIFI

### ISSUE THREAD

**Issue by jackeywoo** [sematext/sematext-logsene-android#3]
Can any configuration could help to make report log ONLY in WIFI  ? Thanks

**Comment by amir-hadzic** [comment]
Hi,

Not at the moment, but it would be fairly trivial to add support for that in [LogWorker.java#L166](https://github.com/sematext/sematext-logsene-android/blob/master/src/main/java/com/sematext/android/LogWorker.java#L166).

**Comment by jackeywoo** [comment]
Thanks for you rapid answer , thanks
