### ISSUE TITLE
How to use timber library

### ISSUE THREAD

**Issue by Taogo-Hugo** [sematext/sematext-logsene-android#33]
Hi,
    How to create timber tree?
    Timber: https://github.com/JakeWharton/timber

**Comment by gr0** [comment]
We don't have any instructions for Timber, but have a look at [https://github.com/JakeWharton/timber/blob/master/timber-sample/src/main/java/com/example/timber/ExampleApp.java](https://github.com/JakeWharton/timber/blob/master/timber-sample/src/main/java/com/example/timber/ExampleApp.java). You can extend the `Timber.Tree` and overwrite the `log` method and include logging using the `Logsene` object there. You would just have to initialize the `Logsene` object in the `onCreate` method and everything should work from that point.

**Comment by Taogo-Hugo** [comment]
Ok, thanks!

**Comment by gr0** [comment]
You're welcome :)
