### ISSUE TITLE
Please use jCenter, not maven

### ISSUE THREAD

**Issue by olivier65** [sematext/sematext-logsene-android#5]
jCenter is now and has been for a while the standard repo expected by gradle on Android. See [this blog post](https://blog.bintray.com/2015/02/09/android-studio-migration-from-maven-central-to-jcenter/).

PS: The Tor Norbye quoted at the end is the head honcho for Android Studio.

**Comment by otisg** [comment]
Shouldn't jCenter now have the latest version we released earlier?  Or maybe it didn't pick it up yet?

**Comment by olivier65** [comment]
Yes, I am seeing it now. Thanks.
